### ISSUE TITLE
generated qr code but it is not qr code , it is like earthwarm

### ISSUE THREAD

**Issue by pipecivil** [awesomejerry/react-native-qrcode-svg#96] opened 2020-03-06 00:19 UTC
what is problem 
<img width="124" alt="스크린샷 2020-03-06 오전 9 17 59" src="https://user-images.githubusercontent.com/4828753/76037859-6f435d00-5f8b-11ea-8ae4-6422a15c1f5d.png">

I using this packages 
    "react-native-camera-kit": "^8.0.4",

    "react-native-qrcode-svg": "^6.0.3",

    "react-native-svg": "^12.0.2",

**Comment by leandrosoaresdesouza** [comment] 2020-03-06 13:30
I'm getting the same problem

**Comment by aeam88** [comment] 2020-03-06 20:02
Same problem with this versions:
"react-native-qrcode-svg": "^6.0.3",
"react-native-svg": "^12.0.2",

Some fix please

**Comment by jhen0409** [comment] 2020-03-07 09:01
It woks fine with `react-native-svg@11.0.1`. We need to find out what happened after upgrading rn-svg to v12.

Note that the issue is only on Android to me.

/cc @awesomejerry

**Comment by jhen0409** [comment] 2020-03-09 00:09
I confirmed the issue have been fixed by `react-native-svg@12.0.3`. (https://github.com/react-native-community/react-native-svg/commit/df4ff9caa7cedfabcbb8e470977ad92db3773830)

**Comment by intitec** [comment] 2020-03-12 02:16
> It woks fine with `react-native-svg@11.0.1`. We need to find out what happened after upgrading rn-svg to v12.
> 
> Note that the issue is only on Android to me.
> 
> /cc @awesomejerry

Confirmed. This version fix the bug.
Apparently, the lines of the QR are rounded using the last version of the react-native-svg

**Comment by intitec** [comment] 2020-03-12 02:29
Confirmed. This version fix the bug.
Apparently, the lines of the QR are rounded using the last version of the react-native-svg

If you get this error: 
`bundling failed: Error: Unable to resolve module ./elements/NativeComponents from node_modules/react-native-svg/src/ReactNativeSVG.ts`

Follow this comment https://github.com/react-native-community/react-native-svg/issues/1165#issuecomment-579276381

**Comment by mathritter** [comment] 2020-04-06 14:57
> 
> 
> Confirmed. This version fix the bug.
> Apparently, the lines of the QR are rounded using the last version of the react-native-svg
> 
> If you get this error:
> `bundling failed: Error: Unable to resolve module ./elements/NativeComponents from node_modules/react-native-svg/src/ReactNativeSVG.ts`
> After downgrading the version of react-native-svg.
> 
> Follow this comment [react-native-community/react-native-svg#1165 (comment)](https://github.com/react-native-community/react-native-svg/issues/1165#issuecomment-579276381)
> 
> > I confirmed the issue have been fixed by `react-native-svg@12.0.3`. ([react-native-community/react-native-svg@df4ff9c](https://github.com/react-native-community/react-native-svg/commit/df4ff9caa7cedfabcbb8e470977ad92db3773830))

How to do that with expo?

**Comment by QuantJames** [comment] 2020-04-16 10:12
I had this issue after upgrading from Expo SDK 33 to 37 (and therefore RN from 0.59 to 0.61). I fixed it by downgrading react-native-svg to 11.0.1.

> > Confirmed. This version fix the bug.
> > Apparently, the lines of the QR are rounded using the last version of the react-native-svg
> > If you get this error:
> > `bundling failed: Error: Unable to resolve module ./elements/NativeComponents from node_modules/react-native-svg/src/ReactNativeSVG.ts`
> > After downgrading the version of react-native-svg.
> > Follow this comment [react-native-community/react-native-svg#1165 (comment)](https://github.com/react-native-community/react-native-svg/issues/1165#issuecomment-579276381)
> > > I confirmed the issue have been fixed by `react-native-svg@12.0.3`. ([react-native-community/react-native-svg@df4ff9c](https://github.com/react-native-community/react-native-svg/commit/df4ff9caa7cedfabcbb8e470977ad92db3773830))
> 
> How to do that with expo?

in your package.json replace react-native-svg dependency row with  `“react-native-svg”: “^11.0.1",` then run `yarn install`.

**Closed** 2020-04-25 02:50 UTC
