### ISSUE TITLE
ld: library not found for -lRNSVG-tvOS

### ISSUE THREAD

**Issue by AndroidIosWebEmbeddedFirmwareDver** [awesomejerry/react-native-qrcode-svg#23] opened 2018-01-03 06:02 UTC
ld: library not found for -lRNSVG-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

HOW TO RESOLVE???

**Comment by msageryd** [comment] 2018-01-03 10:46
Did you use `react-native link`? Sometimes this will link some tvOS stuff to your iOS library in XCode. I don't know when or why. When I get into trouble like this I usually just clean out all tvOS related stuff from the XCode project. I also most often link the libraries manually to avoid problems caused by the `link` command.

Manual linking: https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

**Comment by msageryd** [comment] 2018-01-03 10:47
I found some more info here: https://github.com/facebook/react-native/issues/13783

**Comment by awesomejerry** [comment] 2018-07-05 07:35
I believe this is resolved by using latest version of `react-native-svg`.

**Closed by awesomejerry** 2018-07-05 07:35 UTC
